### ISSUE TITLE
ExtractBundledGGPK3 -  Error on 5 files when reading Content.ggpk (POE 2)

### ISSUE THREAD

**Issue by mtweus** [aianlinb/LibGGPK3#25]
- PoE 2
- Standalone client (not steam/epic)

Code fails on the following command: 

`new BundledGGPK("C:\\Program Files (x86)\\Grinding Gear Games\\Path of Exile 2\\Content.ggpk");`

Error message: 

```
System.IO.InvalidDataException: Parsing path failed for 5 files
   at SystemExtensions.ThrowHelper.Throw[T](Object[] arguments)
   at LibBundle3.Index..ctor(Stream stream, Boolean leaveOpen, Boolean parsePaths, IBundleFactory bundleFactory) in C:\Users\mateu\Downloads\LibGGPK3-2.6.9\LibBundle3\Index.cs:line 206
   at LibBundledGGPK3.BundledGGPK.Ctor(Boolean parsePathsInIndex) in C:\Users\mateu\Downloads\LibGGPK3-2.6.9\LibBundledGGPK3\BundledGGPK.cs:line 25
   at LibBundledGGPK3.BundledGGPK..ctor(String filePath, Boolean parsePathsInIndex) in C:\Users\mateu\Downloads\LibGGPK3-2.6.9\LibBundledGGPK3\BundledGGPK.cs:line 36
   at ExtractBundledGGPK3.Program.Main(String[] args) in C:\Users\mateu\Downloads\LibGGPK3-2.6.9\Examples\ExtractBundledGGPK3\Program.cs:line 50
```

**Comment by mtweus** [comment]
PS: error happens using also the compiled version provided on the release page.. please lmk if im using it the wrong way! appreciate your time.

**Comment by aianlinb** [comment]
Fixed in https://github.com/aianlinb/LibGGPK3/commit/97b791bdff49f038e7d69dc4476f7beed3c2be10
You can build the project yourself if you need.

**Comment by ElRatto** [comment]
this has not fixed it imo. the TryFindNode after still fails because of broken files

**Comment by aianlinb** [comment]
@ElRatto Sorry, fixed in https://github.com/aianlinb/LibGGPK3/commit/a3085b21a57f186450320cbf83ba632c2867e9e9
